ALTER TABLE registro_factura ADD CONSTRAINT reg_pag_fact_fk FOREIGN KEY (id_registro_pago) REFERENCES registro_pago(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE registro_factura ADD CONSTRAINT concept_reg_fact_fk FOREIGN KEY (id_concepto) REFERENCES concepto_pago(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE registro_factura ADD id_empresa bigint;
ALTER TABLE registro_factura ADD id_estado int4;
ALTER TABLE registro_factura ADD CONSTRAINT estado_fact_fk FOREIGN KEY (id_estado) REFERENCES estado_pago(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE registro_factura ADD CONSTRAINT acuerdo_fact_fk FOREIGN KEY (id_acuerdo_pago) REFERENCES acuerdo_pago(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE registro_factura ADD CONSTRAINT cuenta_fact_fk FOREIGN KEY (id_cuenta_proveedor) REFERENCES cuentas_proveedor(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE registro_factura ADD CONSTRAINT empresa_fact_fk FOREIGN KEY (id_empresa) REFERENCES empresa(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE empresa ADD no_licencia varchar(500);
ALTER TABLE registro_factura ADD CONSTRAINT proveedor_fact_fk FOREIGN KEY (id_proveedor) REFERENCES proveedor(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE cuentas_proveedor ADD id_proveedor bigint NOT NULL;
ALTER TABLE cuentas_empresa ADD id_empresa bigint;
ALTER TABLE cuentas_empresa ADD FK_empresa_id bigserial NOT NULL;
ALTER TABLE cuentas_empresa ADD CONSTRAINT empresa_cuenta_fk FOREIGN KEY (FK_empresa_id) REFERENCES empresa(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE cuentas_empresa DROP CONSTRAINT empresa_cuenta_fk;
ALTER TABLE cuentas_empresa ADD CONSTRAINT empresa_cuenta_fk FOREIGN KEY (id_empresa) REFERENCES empresa(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE cuentas_empresa DROP COLUMN FK_empresa_id;
ALTER TABLE cuentas_proveedor ADD CONSTRAINT cuenta_proveedor_fk FOREIGN KEY (id_proveedor) REFERENCES proveedor(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE registro_pago ADD CONSTRAINT cuenta_ori_fk FOREIGN KEY (id_cuenta_origen) REFERENCES cuentas_empresa(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE registro_pago ADD CONSTRAINT cuenta_destino_fk FOREIGN KEY (id_cuenta_destino) REFERENCES cuentas_proveedor(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE registro_pago ADD CONSTRAINT proveedor_pago_fk FOREIGN KEY (id_proveedor) REFERENCES proveedor(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE registro_pago ADD CONSTRAINT empresa_pago_fk FOREIGN KEY (id_empresa) REFERENCES empresa(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE registro_pago ADD CONSTRAINT estado_pago_fk FOREIGN KEY (id_estado) REFERENCES estado_pago(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
