ALTER TABLE registro_pago DROP COLUMN mon_cuenta;
ALTER TABLE registro_pago DROP COLUMN mon_origen;
ALTER TABLE registro_pago DROP COLUMN no_cuenta;
ALTER TABLE registro_pago DROP COLUMN cuenta_origen;
ALTER TABLE registro_pago DROP COLUMN num_id;
ALTER TABLE registro_pago DROP COLUMN nombre;
ALTER TABLE registro_pago DROP COLUMN estado;
ALTER TABLE registro_pago ADD no_detraccion varchar(255);
ALTER TABLE registro_pago ADD id_estado int4;
ALTER TABLE registro_pago RENAME COLUMN otro TO otra_informacion;
ALTER TABLE registro_pago ADD socket_documento varchar(1500);
ALTER TABLE registro_pago ADD id_concepto int4;
ALTER TABLE registro_pago ADD id_proveedor bigint;
ALTER TABLE registro_pago ADD id_cuenta_origen int4;
ALTER TABLE registro_pago ADD serie_factura varchar(255);
ALTER TABLE registro_pago ADD id_cuenta_destino int4;
ALTER TABLE registro_pago ADD desc_destino varchar(255);
ALTER TABLE registro_pago ADD id_empresa bigint;
ALTER TABLE registro_pago RENAME COLUMN fecha TO fecha_pago;
ALTER TABLE registro_pago ADD persona_entrega_fact varchar(1000);
ALTER TABLE registro_pago ADD id_acuerdo_pago int4;
ALTER TABLE registro_pago ADD fecha_entrega_fact date;
ALTER TABLE registro_pago ADD fecha_emision_fact date;
ALTER TABLE registro_pago ADD area_entrega_fact varchar(1000);
DROP INDEX registro_pagos_ui1;
